### ISSUE TITLE
Feature request - Craft3 version

### ISSUE THREAD

**Issue by anchovy** [mmikkel/limitblocktype#4]
Hi,

Looks like something we could use, any chance of a craft3 version?

Thanks in advance.

**Comment by mmikkel** [comment]
Hi @anchovy – I'm still undecided, but I'll probably port it. Will update this issue if/when I do. For the interim, the plugin is MIT so if anybody else wants to pick it up, I'd be totally OK with that :)

**Comment by malcolmhmaclean** [comment]
+1 for this

**Comment by mmikkel** [comment]
Hi @anchovy and @malcolmhmaclean – I'm not going to port this plugin, but the [MatrixMate](https://github.com/vaersaagod/matrixmate) plugin (which was just published to the Plugin Store) [can be used to achieve the same thing as Limit Block Type did](https://github.com/vaersaagod/matrixmate#max-limit).
